Add some new examples in chapter5/5.5
kalfazed/tensorrt_starter pull request #8
Opened 2024-06-07 14:05 UTC by Phoenix8215

## Overview
Hi kalfazed,i have added some new examples in chapter5/5.5.And i have already demonstrated that the network output results between Pytorch and TRT almost the same:-) please review it, 3Q~

### What should reviewers check
i will provide some pictures from the output results(one from Pytorch, another is from TRT)
## How to check
- pooling
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/0922ea9d-bbab-4b15-893c-eda98f311294)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/3c4f5b5c-55ed-46f3-8eef-d5a4808f6ca8)

- upsample
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/3b173f41-ddf7-4ea8-adfb-6ed7beab70f2)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/1837fd3b-0b14-47e2-ab8e-eadfaaafc5a9)

- deconv
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/d235e715-fa3e-478f-a687-fb96f45fb42f)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/d235e715-fa3e-478f-a687-fb96f45fb42f)

- concat
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/bc4a7b58-774d-45e3-a301-513c09c0ba94)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/799fc75e-370c-4257-9a63-6c916fc7ef92)

- elementwise & const
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/e74e5259-8788-4c9d-a5ae-f3cef5c5cebb)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/d03a8bb1-ec2f-43c4-949c-c4fb76816cb6)

- reduce
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/6468a31a-6fd8-4554-9ba3-c5d4489689c1)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/4f07c844-3828-4688-8632-0aa7a5f092e6)

- slice
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/ccaa0e2e-e344-4a20-9a19-39fa3f7f823c)
![图片](https://github.com/kalfazed/tensorrt_starter/assets/37546779/a30c1196-7da4-43ee-9746-8f226180f098)

## Related issues

2024-06-25 14:17 UTC, kalfazed requested changes
Thank you for the contribution and sorry for the late response. Please check the comments above and make some changes? For the other parts, it looks good to me.

2024-06-25 14:17 UTC, kalfazed commented on chapter5-tensorrt-api-basics/5.5-build-model/models/weights/sample_concat.weights
> +4
If all these weights can be reproduced from python code, can you remove all these weights?

2024-06-26 03:10 UTC, Phoenix8215 commented
Hi @kalfazed, 

I have made the requested changes by adding dynamic parameters to the `build_concat` and `build_slice` functions. Additionally, I have removed the unnecessary weights as per your suggestion.

Could you please review the changes again?

Thank you!
🥰

2024-06-26 03:11 UTC, Phoenix8215 commented
and some results for my test🥰(actually the same)
![img_v3_02c7_c0fe94fe-6dfb-462e-ac1d-7eb36e34d8dg](https://github.com/kalfazed/tensorrt_starter/assets/37546779/b1bc3b0a-c483-4455-b957-2df3c21f4434)
![img_v3_02c7_ed7267d5-a4e5-47cb-90c5-e4c81c275c8g](https://github.com/kalfazed/tensorrt_starter/assets/37546779/ac62eeb1-75d5-437a-8f56-8a1df14ed49a)

2024-06-27 08:12 UTC, kalfazed approved these changes
LGTM! It's good to merge now. Thank you for the contribution again!

2024-06-27 14:59 UTC, Phoenix8215 commented
Hi kalfazed,

Thank you for the approval! Unfortunately, I do not have write access to this repository, so I am unable to merge this pull request myself. Could you merge it for me?

Thank you!🥰

2024-06-28 03:37 UTC, merged